# Generated by Django 5.0.6 on 2024-06-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.AddField(
            model_name='account',
            name='credentials',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
