# Generated by Django 5.0.6 on 2024-06-30 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_remove_account_password_account_credentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='platform',
            field=models.CharField(choices=[('yandex', 'Yandex'), ('gmail', 'Gmail'), ('mail.ru', 'Mail.ru')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'email'), name='unique_emails_per_user'),
        ),
    ]
