# Generated by Django 5.0.6 on 2024-07-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_account_platform_account_user_alter_account_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date_received',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_sent',
        ),
        migrations.AddField(
            model_name='message',
            name='box',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('outbox', 'Outbox')], default='inbox'),
        ),
    ]
