# Generated by Django 5.0.6 on 2024-07-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_rename_date_received_message_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='box',
            field=models.CharField(choices=[('inbox', 'Входящие'), ('outbox', 'Отправленные')], default='inbox'),
        ),
    ]
